apiVersion: v1
kind: Secret
metadata:
  name: payments-secret
  namespace: payments
  labels:
    app: payments
type: Opaque
stringData:
  ConnectionStrings__Postgres: "${DB_VAL}"
  AWS__AccessKey: "${KEY_ID}"
  AWS__SecretKey: "${KEY_SECRET}"
  AWS__SessionToken: "${KEY_TOKEN}"

